# -*- coding: utf-8 -*-
"""euler tangents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHheqWh_pzsnoEQct4vRwLZDImQrg3Tz
"""

import math

x_start = -1
y_start =  0
change_in_x = 0.1
n_steps = 14

x = x_start
y = y_start

for i in range (0, n_steps+1):
  print ("step", i)
  print("x: ", x)
  print("y: ", y)
  if i == n_steps:
    break
  dy_dx = round(x+y, 6)
  print("dy/dx" , dy_dx)
  change_in_y = round(dy_dx * change_in_x, 6)
  print("dy", change_in_y)
  x = x+change_in_x
  y = y + change_in_y

